version: '2'
services:
    aze-app:
        image: aze
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://aze-postgresql:5432/aze
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8585:8585
    aze-postgresql:
        extends:
            file: postgresql.yml
            service: aze-postgresql
